/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardListItem: typeof import('./src/components/CardListItem.vue')['default']
    DisplayChip: typeof import('./src/components/DisplayChip.vue')['default']
    LoadingDialog: typeof import('./src/components/LoadingDialog.vue')['default']
    OperatorInspector: typeof import('./src/components/OperatorInspector.vue')['default']
    OperatorNameplate: typeof import('./src/components/OperatorNameplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
  }
}
