/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardListItem: typeof import('./src/components/CardListItem.vue')['default']
    CardListSection: typeof import('./src/components/CardListSection.vue')['default']
    DisplayListItem: typeof import('./src/components/DisplayListItem.vue')['default']
    DisplayListSection: typeof import('./src/components/DisplayListSection.vue')['default']
    LoadingDialog: typeof import('./src/components/LoadingDialog.vue')['default']
    OperatorInspector: typeof import('./src/components/modals/OperatorInspector.vue')['default']
    OperatorNameplate: typeof import('./src/components/OperatorNameplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./src/components/modals/SettingsModal.vue')['default']
  }
}
